import { NextPage } from 'next'
import Head from 'next/head'
// import avatar from '@public/vercel.svg'
// import { Avatar } from '@components/index'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Avatar mode="list" img={avatar} /> */}
    </div>
  )
}

export default Home
